version: '3'
services:
  web-ui: 
    restart: unless-stopped
    build: ./frontend/
    ports: 
      - 3000:3000
    networks: 
      - frontend-nw
    depends_on:
      - api-server
      - mongo

  api-server:
    restart: unless-stopped
    build: ./backend/
    ports: 
      - 5000:5000
    networks:
      - backend-nw
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - 'MONGO_INITDB_DATABASE=todousers'
    volumes: 
      - "mongo_db:/data/db"
      - "mongo_db_config:/data/configdb"
    networks:
      - backend-nw

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8111:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - backend-nw
    depends_on:
      - mongo

networks:
  backend-nw:
    driver: bridge
  frontend-nw:
    driver: bridge

volumes:
  mongo_db:
  mongo_db_config:
    
